import os

RUNS_DIR = "./runs"
DB_FILENAME = "lensnn.db"
DB_PATH = os.path.join(RUNS_DIR, DB_FILENAME)

MAX_ACTIVATION_ARRAY_SIZE = 10_000
PCA_COMPONENTS = 2
GRID_RESOLUTION = 100
CALIBRATION_BINS = 10
SHAP_BACKGROUND_SAMPLES = 100
GRADCAM_MAX_SAMPLES = 8

DEFAULT_SERVER_HOST = "127.0.0.1"
DEFAULT_SERVER_PORT = 8000
